-- =====================================================
-- MIGRACIÓN: Crear tabla lecturas_mensuales_agua
-- Ejecutar este script en Supabase SQL Editor
-- =====================================================

-- Tabla para lecturas mensuales de agua (multi-año)
CREATE TABLE IF NOT EXISTS lecturas_mensuales_agua (
  id BIGSERIAL PRIMARY KEY,
  anio INTEGER NOT NULL,
  mes INTEGER NOT NULL CHECK (mes >= 1 AND mes <= 12),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  
  -- Puntos de medición (mismos que lecturas_semana_agua_2026)
  l_medidor_general_pozos NUMERIC,
  l_pozo_11 NUMERIC,
  l_pozo_14 NUMERIC,
  l_pozo_12 NUMERIC,
  l_pozo_7 NUMERIC,
  l_pozo_3 NUMERIC,
  l_pozo_4_riego NUMERIC,
  l_pozo_8_riego NUMERIC,
  l_pozo_15_riego NUMERIC,
  l_circuito_8_campus NUMERIC,
  l_auditorio_luis_elizondo NUMERIC,
  l_cdb2 NUMERIC,
  l_cdb2_banos_nuevos_2025 NUMERIC,
  l_arena_borrego NUMERIC,
  l_edificio_negocios_daf NUMERIC,
  l_aulas_6 NUMERIC,
  l_domo_cultural NUMERIC,
  l_wellness_parque_central_tunel NUMERIC,
  l_wellness_registro NUMERIC,
  l_parque_central_registro NUMERIC,
  l_wellness_edificio NUMERIC,
  l_wellness_super_salads NUMERIC,
  l_wellness_torre_enfriamiento NUMERIC,
  l_wellness_alberca NUMERIC,
  l_centrales_comedor_1_principal NUMERIC,
  l_centrales_dona_tota NUMERIC,
  l_centrales_subway NUMERIC,
  l_centrales_carls_jr NUMERIC,
  l_centrales_little_cesars NUMERIC,
  l_centrales_grill_team NUMERIC,
  l_centrales_chilaquiles NUMERIC,
  l_centrales_tec_food NUMERIC,
  l_centrales_oxxo NUMERIC,
  l_comedor_central_tunel NUMERIC,
  l_administrativo NUMERIC,
  l_biotecnologia NUMERIC,
  l_escuela_arte_caldera_1 NUMERIC,
  l_ciap_oriente NUMERIC,
  l_ciap_centro NUMERIC,
  l_ciap_poniente NUMERIC,
  l_ciap_green_shake NUMERIC,
  l_ciap_andatti NUMERIC,
  l_ciap_dc_jochos NUMERIC,
  l_aulas_5 NUMERIC,
  l_ciap_starbucks NUMERIC,
  l_ciap_super_salads NUMERIC,
  l_ciap_sotano NUMERIC,
  l_reflexion NUMERIC,
  l_comedor_2_residencias_10_15 NUMERIC,
  l_residencias_10_15 NUMERIC,
  l_residencias_10_15_llenado NUMERIC,
  l_comedor_2_caldera_2 NUMERIC,
  l_la_choza NUMERIC,
  l_cedes_cisterna NUMERIC,
  l_cedes_site NUMERIC,
  l_nucleo NUMERIC,
  l_expedition NUMERIC,
  l_expedition_bread NUMERIC,
  l_expedition_matthew NUMERIC,
  l_cedes_e2 NUMERIC,
  l_aulas_1 NUMERIC,
  l_rectoria_norte NUMERIC,
  l_pabellon_la_carreta NUMERIC,
  l_rectoria_sur NUMERIC,
  l_aulas_2 NUMERIC,
  l_cetec NUMERIC,
  l_biblioteca NUMERIC,
  l_biblioteca_nikkori NUMERIC,
  l_biblioteca_nectar_works NUMERIC,
  l_biblioteca_tim_horton NUMERIC,
  l_biblioteca_starbucks NUMERIC,
  l_aulas_3 NUMERIC,
  l_basanti NUMERIC,
  l_aulas_3_sr_latino NUMERIC,
  l_aulas_3_starbucks NUMERIC,
  l_centrales_sur NUMERIC,
  l_aulas_4_norte NUMERIC,
  l_circuito_6_residencias NUMERIC,
  l_residencias_1_antiguo NUMERIC,
  l_residencias_2_ote NUMERIC,
  l_residencias_2_pte NUMERIC,
  l_residencias_3 NUMERIC,
  l_residencias_4 NUMERIC,
  l_residencias_5 NUMERIC,
  l_residencias_7 NUMERIC,
  l_residencias_8 NUMERIC,
  l_correos NUMERIC,
  l_alberca NUMERIC,
  l_residencias_abc NUMERIC,
  l_circuito_4_a7_ce NUMERIC,
  l_aulas_7 NUMERIC,
  l_cah3_torre_enfriamiento NUMERIC,
  l_caldera_3 NUMERIC,
  l_la_dia NUMERIC,
  l_aulas_4_sur NUMERIC,
  l_aulas_4_maestros NUMERIC,
  l_centro_congresos NUMERIC,
  l_jubileo NUMERIC,
  l_aulas_4_oxxo NUMERIC,
  l_circuito_planta_fisica NUMERIC,
  l_arquitectura_e1 NUMERIC,
  l_arquitectura_anexo NUMERIC,
  l_megacentral_te_2 NUMERIC,
  l_escamilla_banos_trabajadores NUMERIC,
  l_estadio_banorte NUMERIC,
  l_estadio_banorte_te NUMERIC,
  l_campus_norte_edificios_ciudad NUMERIC,
  l_estadio_azul NUMERIC,
  l_circuito_megacentral NUMERIC,
  l_megacentral_te_4 NUMERIC,
  l_ptar_riego NUMERIC,
  l_pozo_4_riego_alt NUMERIC,
  l_pozo_8_riego_alt NUMERIC,
  l_pozo_15_riego_alt NUMERIC,
  l_campus_norte_ciudad_riego NUMERIC,
  l_comedor_d_ciudad NUMERIC,
  l_estadio_banorte_purgas NUMERIC,
  l_wellness_cisterna_pluvial_purgas NUMERIC,
  l_wellness_suavizador_purga NUMERIC,
  l_wellness_te_rebosadero NUMERIC,
  l_wellness_te_purga NUMERIC,
  l_cedes_tinaco_riego_pluvial NUMERIC,
  l_megacentral_te_purgas NUMERIC,
  l_megacentral_suavizador_purga NUMERIC,
  l_cah3_te_purgas NUMERIC,
  l_residencias_10_15_te_purga NUMERIC,
  l_estadio_borrego_pluvial NUMERIC,
  l_ciap_cisterna_pluvial NUMERIC,
  l_campo_soft_bol NUMERIC,
  l_cedes_ciudad NUMERIC,
  l_estacionamiento_e3 NUMERIC,
  l_guarderia NUMERIC,
  l_naranjos NUMERIC,
  l_casa_solar NUMERIC,
  l_escamilla_banos_alumnos NUMERIC,
  l_residencias_11_ciudad NUMERIC,
  l_residencias_12_ciudad NUMERIC,
  l_residencias_13_1_ciudad NUMERIC,
  l_residencias_13_2_ciudad NUMERIC,
  l_residencias_13_3_ciudad NUMERIC,
  l_residencias_15_sotano NUMERIC,
  l_residencias_10_15_purga_no NUMERIC,
  l_cdb1_jardineros NUMERIC,
  l_edificio_d NUMERIC,
  l_estadio_yarda NUMERIC,
  l_farnville NUMERIC,
  l_em_box NUMERIC,
  l_crepaso NUMERIC,
  l_el_negro NUMERIC,
  l_e2_beiker NUMERIC,
  l_e2_evobike NUMERIC,
  l_e2_pancho_de_rigo NUMERIC,
  l_e2_bebedero_nube NUMERIC,
  l_residencias_abc_lavanderia NUMERIC,
  l_estacionamiento_e1 NUMERIC,
  
  -- Constraint único para evitar duplicados de año-mes
  CONSTRAINT unique_anio_mes UNIQUE (anio, mes)
);

-- Índices para búsquedas eficientes
CREATE INDEX IF NOT EXISTS idx_lecturas_mensuales_agua_anio ON lecturas_mensuales_agua(anio);
CREATE INDEX IF NOT EXISTS idx_lecturas_mensuales_agua_mes ON lecturas_mensuales_agua(mes);
CREATE INDEX IF NOT EXISTS idx_lecturas_mensuales_agua_anio_mes ON lecturas_mensuales_agua(anio, mes);

-- Comentario de la tabla
COMMENT ON TABLE lecturas_mensuales_agua IS 'Lecturas mensuales de medidores de agua del campus - Tabla multi-año';

-- =====================================================
-- TABLA DE CONSUMO MENSUAL (calculado)
-- =====================================================

CREATE TABLE IF NOT EXISTS lecturas_mensuales_agua_consumo (
  id BIGSERIAL PRIMARY KEY,
  anio INTEGER NOT NULL,
  mes INTEGER NOT NULL CHECK (mes >= 1 AND mes <= 12),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  
  -- Puntos de medición - consumo calculado (lectura actual - lectura anterior)
  l_medidor_general_pozos NUMERIC,
  l_pozo_11 NUMERIC,
  l_pozo_14 NUMERIC,
  l_pozo_12 NUMERIC,
  l_pozo_7 NUMERIC,
  l_pozo_3 NUMERIC,
  l_pozo_4_riego NUMERIC,
  l_pozo_8_riego NUMERIC,
  l_pozo_15_riego NUMERIC,
  l_circuito_8_campus NUMERIC,
  l_auditorio_luis_elizondo NUMERIC,
  l_cdb2 NUMERIC,
  l_cdb2_banos_nuevos_2025 NUMERIC,
  l_arena_borrego NUMERIC,
  l_edificio_negocios_daf NUMERIC,
  l_aulas_6 NUMERIC,
  l_domo_cultural NUMERIC,
  l_wellness_parque_central_tunel NUMERIC,
  l_wellness_registro NUMERIC,
  l_parque_central_registro NUMERIC,
  l_wellness_edificio NUMERIC,
  l_wellness_super_salads NUMERIC,
  l_wellness_torre_enfriamiento NUMERIC,
  l_wellness_alberca NUMERIC,
  l_centrales_comedor_1_principal NUMERIC,
  l_centrales_dona_tota NUMERIC,
  l_centrales_subway NUMERIC,
  l_centrales_carls_jr NUMERIC,
  l_centrales_little_cesars NUMERIC,
  l_centrales_grill_team NUMERIC,
  l_centrales_chilaquiles NUMERIC,
  l_centrales_tec_food NUMERIC,
  l_centrales_oxxo NUMERIC,
  l_comedor_central_tunel NUMERIC,
  l_administrativo NUMERIC,
  l_biotecnologia NUMERIC,
  l_escuela_arte_caldera_1 NUMERIC,
  l_ciap_oriente NUMERIC,
  l_ciap_centro NUMERIC,
  l_ciap_poniente NUMERIC,
  l_ciap_green_shake NUMERIC,
  l_ciap_andatti NUMERIC,
  l_ciap_dc_jochos NUMERIC,
  l_aulas_5 NUMERIC,
  l_ciap_starbucks NUMERIC,
  l_ciap_super_salads NUMERIC,
  l_ciap_sotano NUMERIC,
  l_reflexion NUMERIC,
  l_comedor_2_residencias_10_15 NUMERIC,
  l_residencias_10_15 NUMERIC,
  l_residencias_10_15_llenado NUMERIC,
  l_comedor_2_caldera_2 NUMERIC,
  l_la_choza NUMERIC,
  l_cedes_cisterna NUMERIC,
  l_cedes_site NUMERIC,
  l_nucleo NUMERIC,
  l_expedition NUMERIC,
  l_expedition_bread NUMERIC,
  l_expedition_matthew NUMERIC,
  l_cedes_e2 NUMERIC,
  l_aulas_1 NUMERIC,
  l_rectoria_norte NUMERIC,
  l_pabellon_la_carreta NUMERIC,
  l_rectoria_sur NUMERIC,
  l_aulas_2 NUMERIC,
  l_cetec NUMERIC,
  l_biblioteca NUMERIC,
  l_biblioteca_nikkori NUMERIC,
  l_biblioteca_nectar_works NUMERIC,
  l_biblioteca_tim_horton NUMERIC,
  l_biblioteca_starbucks NUMERIC,
  l_aulas_3 NUMERIC,
  l_basanti NUMERIC,
  l_aulas_3_sr_latino NUMERIC,
  l_aulas_3_starbucks NUMERIC,
  l_centrales_sur NUMERIC,
  l_aulas_4_norte NUMERIC,
  l_circuito_6_residencias NUMERIC,
  l_residencias_1_antiguo NUMERIC,
  l_residencias_2_ote NUMERIC,
  l_residencias_2_pte NUMERIC,
  l_residencias_3 NUMERIC,
  l_residencias_4 NUMERIC,
  l_residencias_5 NUMERIC,
  l_residencias_7 NUMERIC,
  l_residencias_8 NUMERIC,
  l_correos NUMERIC,
  l_alberca NUMERIC,
  l_residencias_abc NUMERIC,
  l_circuito_4_a7_ce NUMERIC,
  l_aulas_7 NUMERIC,
  l_cah3_torre_enfriamiento NUMERIC,
  l_caldera_3 NUMERIC,
  l_la_dia NUMERIC,
  l_aulas_4_sur NUMERIC,
  l_aulas_4_maestros NUMERIC,
  l_centro_congresos NUMERIC,
  l_jubileo NUMERIC,
  l_aulas_4_oxxo NUMERIC,
  l_circuito_planta_fisica NUMERIC,
  l_arquitectura_e1 NUMERIC,
  l_arquitectura_anexo NUMERIC,
  l_megacentral_te_2 NUMERIC,
  l_escamilla_banos_trabajadores NUMERIC,
  l_estadio_banorte NUMERIC,
  l_estadio_banorte_te NUMERIC,
  l_campus_norte_edificios_ciudad NUMERIC,
  l_estadio_azul NUMERIC,
  l_circuito_megacentral NUMERIC,
  l_megacentral_te_4 NUMERIC,
  l_ptar_riego NUMERIC,
  l_pozo_4_riego_alt NUMERIC,
  l_pozo_8_riego_alt NUMERIC,
  l_pozo_15_riego_alt NUMERIC,
  l_campus_norte_ciudad_riego NUMERIC,
  l_comedor_d_ciudad NUMERIC,
  l_estadio_banorte_purgas NUMERIC,
  l_wellness_cisterna_pluvial_purgas NUMERIC,
  l_wellness_suavizador_purga NUMERIC,
  l_wellness_te_rebosadero NUMERIC,
  l_wellness_te_purga NUMERIC,
  l_cedes_tinaco_riego_pluvial NUMERIC,
  l_megacentral_te_purgas NUMERIC,
  l_megacentral_suavizador_purga NUMERIC,
  l_cah3_te_purgas NUMERIC,
  l_residencias_10_15_te_purga NUMERIC,
  l_estadio_borrego_pluvial NUMERIC,
  l_ciap_cisterna_pluvial NUMERIC,
  l_campo_soft_bol NUMERIC,
  l_cedes_ciudad NUMERIC,
  l_estacionamiento_e3 NUMERIC,
  l_guarderia NUMERIC,
  l_naranjos NUMERIC,
  l_casa_solar NUMERIC,
  l_escamilla_banos_alumnos NUMERIC,
  l_residencias_11_ciudad NUMERIC,
  l_residencias_12_ciudad NUMERIC,
  l_residencias_13_1_ciudad NUMERIC,
  l_residencias_13_2_ciudad NUMERIC,
  l_residencias_13_3_ciudad NUMERIC,
  l_residencias_15_sotano NUMERIC,
  l_residencias_10_15_purga_no NUMERIC,
  l_cdb1_jardineros NUMERIC,
  l_edificio_d NUMERIC,
  l_estadio_yarda NUMERIC,
  l_farnville NUMERIC,
  l_em_box NUMERIC,
  l_crepaso NUMERIC,
  l_el_negro NUMERIC,
  l_e2_beiker NUMERIC,
  l_e2_evobike NUMERIC,
  l_e2_pancho_de_rigo NUMERIC,
  l_e2_bebedero_nube NUMERIC,
  l_residencias_abc_lavanderia NUMERIC,
  l_estacionamiento_e1 NUMERIC,
  
  -- Constraint único para evitar duplicados de año-mes
  CONSTRAINT unique_consumo_anio_mes UNIQUE (anio, mes)
);

-- Índices para tabla de consumo
CREATE INDEX IF NOT EXISTS idx_lecturas_mensuales_agua_consumo_anio ON lecturas_mensuales_agua_consumo(anio);
CREATE INDEX IF NOT EXISTS idx_lecturas_mensuales_agua_consumo_mes ON lecturas_mensuales_agua_consumo(mes);

-- Comentario de la tabla de consumo
COMMENT ON TABLE lecturas_mensuales_agua_consumo IS 'Consumo mensual calculado de medidores de agua del campus - Tabla multi-año';
